name = input("Hello what is your name?")
print(f"Hello {name} today i'm going to need your help to make a story!")
print("")
place = input("first pick a place:")
person = input("now pick a person:")
adjective = input("perfect, now pick an adjective:")
noun = input("now pick a noun:")
forgottennoun = input("ok now pick another noun:")
noun2 = input("ok now pick one more noun:")
number = input("please pick a number now:")
noun3 = input("now pick a fourth noun:")
food = input("pick a food now:")
verb = input("last but not least pick a verb:")
print("")
print("Now it is finally time to hear your story!")
print("")
print(f"I went to the beach in {place} today with {person}.We had a/an {adjective} time.")
print("")
print(f"First we built a {noun} and then we ran around in the {forgottennoun} for a little while.")
print("")
print(f"The water was a bit {noun2} so we left about {number} minutes later.")
print(f"after we left we went to {noun3} and ate {food} and then we {verb} all the way home!")
print(f"OMG thank you so much fro playing my madlibs game {name} that was so much fun!")
print("feel free to play again soon!")



